### ISSUE TITLE
Unable to withdraw stake from CEW due to Trezor firmware 1.8.0 update issue

### ISSUE THREAD

**Issue by redmac68** [CallistoNetwork/ClassicEtherWallet#1]
I have been using TREZOR with CEW for CLO staking. Worked amazingly well until I applied Trezor firmware update 1.8.0. Now I get a message "The current version of firmware (1.8.0) may be not compatible with the running version of Trezor Connect. The current version of firmware contains major changes that could affect the efficient functionality of Trezor Connect." Withdraw of stake is not working now.
Is it planned to update CEW with the latest Trezor Connect version?

**Comment by yograterol** [comment]
Working on it.

**Comment by yograterol** [comment]
@redmac68 please try again.

**Comment by redmac68** [comment]
Hi, I can't retest exactly because I had managed to withdraw using MEW and entering the staking contract details manually so that I could send to Coinomi wallet and restake there. But I have just tested staking some CLO in CEW using the "Start Staking" button and my Trezor with firmware 1.8.0 and this worked perfectly. So I expect that all works now ... but I'm sorry that I can't confirm definitively. Thanks very much for the follow up.

**Comment by redmac68** [comment]
I can check fully in 27 days if needed.

**Comment by ghost** [comment]
Confirmed it solves issue with Trezor one@1.8.0 firmware.

**Comment by yograterol** [comment]
@btenterprise2020 great! cc @redmac68

**Comment by dnlhwrd3269** [comment]
Mine was on my Magnum wall and it was going but it never deposits and thing to my wallet and I got and I have a cew wallet to and I can't get them on that one I had a bunch of coming at one time
